server:
  port: 8090
spring:
  datasource:
    url: "$DB_URL"
    username: "$DB_USER"
    password: "$DB_PASSWORD"
    driver-class-name: com.mysql.cj.jdbc.Driver
    timeout: 60000
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
  flyway:
    enabled: true

  logging:
    level:
      org.hibernate.SQL: debug

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

amazonProperties:
  endpointUrl: "$AWS_ENDPOINT"
  accessKey: "$AWS_ACCESS_KEY"
  secretKey: "$AWS_SECRET_KEY"
  bucketName: "$AWS_BUCKET"
