name: Backend
run-name: ¡Desplegando Backend!

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set Maven Version
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: Setting Variables
      run: |
              export DB_URL=${{ vars.DB_URL }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
              export DB_USER=${{ secrets.DB_USER }}
              export AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
              export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
              export AWS_BUCKET=${{ secrets.AWS_BUCKET }}
              export AWS_ENDPOINT=${{ secrets.AWS_ENDPOINT }}
              
    - name: Build with Maven
      run: mvn -B package --file /home/ubuntu/actions-runner/_work/Eventify-BackEnd/Eventify-BackEnd/pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/_work/Eventify-BackEnd/Eventify-BackEnd/target/eventify-0.0.1-SNAPSHOT.jar &
