name: Backend
run-name: ¡Desplegando Backend!

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USER: ${{ secrets.DB_USER }}

    steps:
    - name: Echo Variables
      run: |
              echo "$DB_URL"
              echo $DB_PASSWORD
              echo $DB_USER
              echo $AWS_SECRET_KEY
              echo $AWS_ACCESS_KEY
              echo $AWS_BUCKET
              echo $AWS_ENDPOINT
              echo "Hola Mundo"
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Set Maven Version
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.8.2
    - name: Build with Maven
      run: mvn -B package --file /home/ubuntu/actions-runner/_work/Eventify-BackEnd/Eventify-BackEnd/pom.xml
    - name: Execute Jar File
      run: sudo kill -9 `sudo lsof -t -i:80` & sudo java -jar /home/ubuntu/actions-runner/_work/Eventify-BackEnd/Eventify-BackEnd/target/evently-0.0.1-SNAPSHOT.jar &
